[general]
# Path to where to save downloaded third party data. To move the data out of the
# standard location use a symbolic link, or change this path. This variable
# is used by the scripts, but not QGIS.
#in_3p_path = data/v1-0/in-3p
#version = v1-0

in_3p_path = data/v1-0/in-3p
version = v1-0