"""
This script combines the multiple validation batches into a single file for each validator.
This combines the batches generated by 20-v0-4-generate-validation-batches.py. This
VALIDATION_PATH_BASE/{Validator} directory contains the following files:
NW-Aus-Features-v0-4_Feature-centroid-{Batch}_{Validator}.shp
NW-Aus-Features-v0-4_Boundary-error-{Batch}_{Validator}.shp

Batches are zero padded two digits, e.g. 00, 01, ..., 09, 10

For each validator and shapefile type, all batches are merged into a single shapefile
and saved in the working directory with the following names:
NW-Aus-Features-v0-4_Feature-centroid_{Validator}.shp
NW-Aus-Features-v0-4_Boundary-error_{Validator}.shp
"""
VERSION = "v0-4"
WORKING_PATH = "working/21"
VALIDATORS = ['EL', 'RB']
VALIDATION_PATH_BASE = f"data/{VERSION}/in/validation/"

import os
import glob
import geopandas as gpd
import pandas as pd

os.makedirs(WORKING_PATH, exist_ok=True)

SHAPEFILE_TYPES = ["Feature-centroid", "Boundary-error"]
BATCH_SIZE = 171  # Set this to the known batch size

# Stage 1: Merge batches and adjust ValidID (keep in memory)
for validator in VALIDATORS:
    validator_dir = os.path.join(VALIDATION_PATH_BASE, validator)
    merged_gdfs = {}
    for shapefile_type in SHAPEFILE_TYPES:
        pattern = f"NW-Aus-Features-{VERSION}_{shapefile_type}-??_{validator}.shp"
        search_path = os.path.join(validator_dir, pattern)
        batch_files = sorted(glob.glob(search_path))
        if not batch_files:
            print(f"No files found for {validator} {shapefile_type}")
            continue
        gdf_list = []
        for batch_no, shp in enumerate(batch_files):
            gdf = gpd.read_file(shp)
            if 'ValidID' in gdf.columns:
                gdf['ValidID'] = gdf['ValidID'] + batch_no * BATCH_SIZE
            gdf_list.append(gdf)
        merged_gdf = gpd.GeoDataFrame(pd.concat(gdf_list, ignore_index=True), crs=gdf_list[0].crs)
        merged_gdfs[shapefile_type] = merged_gdf
        print(f"Merged {len(batch_files)} batches for {validator} {shapefile_type}")

    # Stage 2: Filter Boundary-error by FeatExists in Feature-centroid
    if all(stype in merged_gdfs for stype in SHAPEFILE_TYPES):
        fc_gdf = merged_gdfs['Feature-centroid']
        be_gdf = merged_gdfs['Boundary-error']
        # Convert FeatExists to boolean
        print(f"[DEBUG] {validator}: Unique FeatExists values before conversion: {fc_gdf['FeatExists'].unique()}")
        fc_gdf['FeatExists'] = fc_gdf['FeatExists'].astype(str).str.lower() == 'true'
        print(f"[DEBUG] {validator}: Unique FeatExists values after conversion: {fc_gdf['FeatExists'].unique()}")
        print(f"[DEBUG] {validator}: Feature-centroid total features: {len(fc_gdf)}")
        print(f"[DEBUG] {validator}: Boundary-error total features: {len(be_gdf)}")
        print(f"[DEBUG] {validator}: Feature-centroid unique ValidID: {fc_gdf['ValidID'].nunique()}")
        print(f"[DEBUG] {validator}: Boundary-error unique ValidID: {be_gdf['ValidID'].nunique()}")
        valid_feat_ids = set(fc_gdf.loc[fc_gdf['FeatExists'] == True, 'ValidID'])
        print(f"[DEBUG] {validator}: ValidIDs with FeatExists==True: {len(valid_feat_ids)}")
        print(f"[DEBUG] {validator}: Sample of ValidIDs with FeatExists==True: {list(valid_feat_ids)[:10]}")
        print(f"[DEBUG] {validator}: Boundary-error features before filtering: {len(be_gdf)}")
        filtered_be_gdf = be_gdf[be_gdf['ValidID'].isin(valid_feat_ids)].copy()
        print(f"[DEBUG] {validator}: Boundary-error features after filtering: {len(filtered_be_gdf)}")
        if len(filtered_be_gdf) > 0:
            print(f"[DEBUG] {validator}: Filtered Boundary-error geometry type: {filtered_be_gdf.geometry.iloc[0].geom_type}")
        else:
            print(f"[DEBUG] {validator}: Filtered Boundary-error is empty!")
        # Save filtered Boundary-error as final output
        out_name = f"NW-Aus-Features-{VERSION}_Boundary-error_{validator}.shp"
        out_path = os.path.join(WORKING_PATH, out_name)
        filtered_be_gdf.to_file(out_path)
        print(f"Filtered Boundary-error saved to {out_path}")
        # Also save the merged Feature-centroid as final output
        out_name_fc = f"NW-Aus-Features-{VERSION}_Feature-centroid_{validator}.shp"
        out_path_fc = os.path.join(WORKING_PATH, out_name_fc)
        fc_gdf.to_file(out_path_fc)
        print(f"Feature-centroid saved to {out_path_fc}")