"""
Script: 09c-qaqc-assess-boundary-error.py

Description:
This script assesses the positional accuracy of reef boundary data by comparing boundary error
truth points (gtp) against a matching boundary polygon. The script performs the following steps:

1. **Finding Closest Boundary Edge to Boundary Error Truth Points**:
   - For each point in the boundary error truth points shapefile (which corresponds to manually
     adjusted points matching the true reef boundary), the script finds the closest point on the
     nearest polygon boundary. This includes points located along the edges between vertices, providing
     sub-meter accuracy.

2. **Calculating Positional Errors**:
   - Calculates the geodetic distance (in meters) between each boundary error truth point and its
     corresponding closest point on the polygon boundary (matching point).

3. **Assigning Regions**:
   - Assigns each point to a region based on a provided regions shapefile. This allows for regional
     analysis of positional errors.

4. **Output**:
   - Saves a CSV file containing gtp coordinates, matching coordinates, IDs, errors, and region
     information to OUTPUT_DIR.
   - Saves a shapefile of the matching points generated during the analysis to
     OUTPUT_DIR for verification and visualization purposes.
   - Generates summary statistics describing the distribution of errors per region, including mean,
     median, standard deviation, percentiles, and the number of points used (`n`).
   - Generates a cumulative distribution function (CDF) plot of the distance errors with an overlaid
     cumulative distribution curve, saved as a PNG file to the output directory.

Arguments:
    --input       Path to the original polygon shapefile to process. This polygon represents the
                  matching boundary against which positional accuracy is assessed.
    --gtp         Path to the ground truth points shapefile. These points are manually adjusted to match
                  the true reef boundary. These are generated by 07b.
    --regions     Path to the study region shapefile used to assign regions to points.

Assess the reef boundary mapping against validation points by Rachel Bycroft, using the 12 regions
used to spatially subdivide the reef mapping study area. 
V0-4
python 22-v0-4-assess-boundary-error.py --input data/v0-4/out/NW-Aus-Features_v0-4.shp --gtp working/21/NW-Aus-Features-v0-4_Boundary-error_RB.shp --regions data/v0-4/in/validation/NW-Aus-Features-validation-regions.shp

Rough mask
python 22-v0-4-assess-boundary-error.py --input data/v0-1_dual-maps/Reef-mask_Ref2_EL/AU_AIMS_NESP-MaC-3-17_Rough-reef-shallow-mask_87hr.shp --gtp working/21/NW-Aus-Features-v0-4_Boundary-error_RB.shp --regions data/v0-4/in/validation/NW-Aus-Features-validation-regions.shp

V0-1 RB
python 22-v0-4-assess-boundary-error.py --input "data/v0-1_dual-maps/Reef-Features_Ref1_RB/Reef Boundaries RB.shp" --gtp working/21/NW-Aus-Features-v0-4_Boundary-error_RB.shp --regions data/v0-4/in/validation/NW-Aus-Features-validation-regions.shp

Notes:
- The matching points are saved for verification, allowing users to visualize and check the points
  found by the script.
"""
import geopandas as gpd
import pandas as pd
import os
import argparse
from geopy.distance import geodesic
import matplotlib.pyplot as plt
import numpy as np
from shapely.geometry import Point, Polygon, MultiPolygon
from shapely.ops import nearest_points
import warnings
from tqdm import tqdm  # For progress indication

warnings.filterwarnings("ignore", category=UserWarning)  # Suppress CRS mismatch warnings

# Define all assessments to run
# edge_acc_var is the name of the variable in the input shapefile that contains edge accuracy in meters. If
# set to None there there is no attribute available.
ASSESSMENTS = [
    
    {
        "name": "V0-1 EL",
        "input": "data/v0-1_dual-maps/Reef-mask_Ref2_EL/AU_AIMS_NESP-MaC-3-17_Rough-reef-shallow-mask_87hr.shp",
        "gtp": "working/21/NW-Aus-Features-v0-4_Boundary-error_RB.shp",
        "regions": "data/v0-4/in/validation/NW-Aus-Features-validation-regions.shp",
        "output_dir": "working/V03/v0-1-EL",
        "edge_acc_var": None
    },
    {
        "name": "V0-1 RB",
        "input": "data/v0-1_dual-maps/Reef-Features_Ref1_RB/Reef Boundaries RB.shp",
        "gtp": "working/21/NW-Aus-Features-v0-4_Boundary-error_RB.shp",
        "regions": "data/v0-4/in/validation/NW-Aus-Features-validation-regions.shp",
        "output_dir": "working/V03/v0-1-RB",
        "edge_acc_var": "Edg_acc"
    },
    {
        "name": "V0-2 merge",
        "input": "data/v0-2_merge-maps/Reef-boundaries-v0-2/Reef Boundaries Review RB.shp",
        "gtp": "working/21/NW-Aus-Features-v0-4_Boundary-error_RB.shp",
        "regions": "data/v0-4/in/validation/NW-Aus-Features-validation-regions.shp",
        "output_dir": "working/V03/v0-2",
        "edge_acc_var": "Edg_acc"
    },
    {
        "name": "V0-3 qaqc",
        "input": "data/v0-3_qc-1/out/NW-Aus-Features_v0-3.shp",
        "gtp": "working/21/NW-Aus-Features-v0-4_Boundary-error_RB.shp",
        "regions": "data/v0-4/in/validation/NW-Aus-Features-validation-regions.shp",
        "output_dir": "working/V03/v0-3",
        "edge_acc_var": "EdgeAcc_m"
    },
    {
        "name": "V0-4 qaqc",
        "input": "data/v0-4/out/AU_NESP-MaC-3-17_AIMS_NW-Aus-Features_v0-4.shp",
        "gtp": "working/21/NW-Aus-Features-v0-4_Boundary-error_RB.shp",
        "regions": "data/v0-4/in/validation/NW-Aus-Features-validation-regions.shp",
        "output_dir": "working/V03/v0-4",
        "edge_acc_var": "EdgeAcc_m"
    }
]


# Define max_distance in degrees for a polygon to be considered as a match.
# For 3 km, in degrees at equator: 3 km / 111 km per degree ~ 0.027 degrees
MAX_MATCH_DISTANCE_DEG = 0.01

# Increase font sizes by 20%
TITLE_FONTSIZE = 14
LABEL_FONTSIZE = 12
TICK_FONTSIZE = 12
LEGEND_FONTSIZE = 12

def assign_regions(points_gdf, regions_shp):
    """
    Assign regions to points based on spatial join with region polygons.
    Adds debug output to help diagnose missing region assignments.
    """
    regions_gdf = gpd.read_file(regions_shp)
    print("[DEBUG] Unique RegionName values in regions shapefile:", regions_gdf['RegionName'].unique())
    print("[DEBUG] Unique RegionID values in regions shapefile:", regions_gdf['RegionID'].unique() if 'RegionID' in regions_gdf.columns else 'RegionID column not found')
    print("[DEBUG] Regions shapefile CRS:", regions_gdf.crs)
    print("[DEBUG] Points CRS:", points_gdf.crs)
    points_with_regions = gpd.sjoin(points_gdf, regions_gdf, how='left', predicate='intersects')
    print("[DEBUG] After spatial join, unique RegionName values:", points_with_regions['RegionName'].unique())
    print("[DEBUG] Number of points with no region assigned (RegionName is NaN):", points_with_regions['RegionName'].isna().sum())
    if points_with_regions['RegionName'].isna().sum() > 0:
        print("[DEBUG] Sample of points with no region assigned:")
        print(points_with_regions[points_with_regions['RegionName'].isna()].head())
    return points_with_regions


def generate_matching_points(polygon_gdf, gtp_gdf, edge_acc_var=None):
    """
    Generates matching points by finding the closest point on the nearest polygon boundary
    for each point in gtp_gdf. Optionally extracts edge accuracy attribute.
    """
    polygon_gdf = polygon_gdf.reset_index(drop=True)
    polygon_sindex = polygon_gdf.sindex
    match_points = []
    print(f"Finding closest points for {len(gtp_gdf)} gtp points...")

    for idx, row in tqdm(gtp_gdf.iterrows(), total=gtp_gdf.shape[0], desc="Processing points"):
        point = row.geometry
        indices = polygon_sindex.nearest([point], return_all=False, max_distance=MAX_MATCH_DISTANCE_DEG, return_distance=False)
        if len(indices[1]) == 0:
            continue
        nearest_polygon_index = indices[1][0]
        nearest_polygon = polygon_gdf.geometry.iloc[nearest_polygon_index]
        boundary = nearest_polygon.boundary
        nearest_point = nearest_points(point, boundary)[1]

        edge_acc_val = None
        if edge_acc_var and edge_acc_var in polygon_gdf.columns:
            try:
                edge_acc_val = float(polygon_gdf.iloc[nearest_polygon_index][edge_acc_var])
            except (ValueError, TypeError):
                edge_acc_val = None

        match_points.append({
            "ValidID": row["ValidID"],
            "PolyIdx": nearest_polygon_index,
            "EdgeAcc_m": edge_acc_val,
            "geometry": nearest_point
        })

    match_gdf = gpd.GeoDataFrame(match_points, crs=gtp_gdf.crs)
    return match_gdf

def calculate_distances_with_regions(polygon_shp, gtp_file, regions_shp, output_csv, match_points_shp, edge_acc_var=None):
    # Load the gtp points shapefile
    gtp_gdf = gpd.read_file(gtp_file)

    # Load the polygon shapefile
    polygon_gdf = gpd.read_file(polygon_shp)

    # Ensure CRS matches
    if polygon_gdf.crs != gtp_gdf.crs:
        polygon_gdf = polygon_gdf.to_crs(gtp_gdf.crs)

    # Generate the matching points
    print("Generating matching points by finding closest points on the nearest polygon boundary...")
    match_gdf = generate_matching_points(polygon_gdf, gtp_gdf, edge_acc_var=edge_acc_var)

    # Initialize results list
    results = []

    # Process each gtp point
    print("Calculating distances and updating match points with error values...")
    for idx, gtp_point in tqdm(gtp_gdf.iterrows(), total=gtp_gdf.shape[0], desc="Processing points"):
        gtp_coords = (gtp_point.geometry.y, gtp_point.geometry.x)
        match_point = match_gdf[match_gdf["ValidID"] == gtp_point["ValidID"]]

        # Initialize result entry
        result = {
            "ValidID": gtp_point["ValidID"],
            "ActLat": gtp_coords[0],
            "ActLon": gtp_coords[1],
            "MatchLat": None,
            "MatchLon": None,
            "Error_m": None,
            "EdgeAcc_m": None,
            "MatchFnd": False
        }

        # If a match is found, calculate the error and update match_gdf
        if not match_point.empty:
            match_coords = (match_point.iloc[0].geometry.y, match_point.iloc[0].geometry.x)
            distance_m = geodesic(gtp_coords, match_coords).meters
            result.update({
                "MatchLat": match_coords[0],
                "MatchLon": match_coords[1],
                "Error_m": distance_m,
                "EdgeAcc_m": match_point.iloc[0].get("EdgeAcc_m", None),
                "MatchFnd": True
            })
            match_gdf.loc[match_gdf["ValidID"] == gtp_point["ValidID"], "Error_m"] = distance_m

        results.append(result)

    # Save the matching points with Error_m to a shapefile
    match_gdf.to_file(match_points_shp)
    print(f"Matching points with errors saved to {match_points_shp}")

    # Create a GeoDataFrame for the results
    results_df = pd.DataFrame(results)
    results_gdf = gpd.GeoDataFrame(
        results_df,
        geometry=gpd.points_from_xy(results_df["ActLon"], results_df["ActLat"]),
        crs=gtp_gdf.crs
    )

    # Assign regions to points
    distances_with_regions = assign_regions(results_gdf, regions_shp)
    print("[DEBUG] Region assignment counts after join:")
    print(distances_with_regions['RegionName'].value_counts(dropna=False))

    # Drop unnecessary columns
    distances_with_regions = distances_with_regions.drop(columns=["geometry", "index_right", "id"], errors="ignore")

    # Save to CSV
    distances_with_regions.to_csv(output_csv, index=False)
    print(f"Results saved to {output_csv}")
    return distances_with_regions
    

def output_error_statistics_by_region(errors_gdf):
    """
    Compute and print error statistics per region, including unmatched locations.
    """
    # Use RegionName directly for grouping (do not combine RemoteReefs and NorthernAU)
    errors_gdf["RegionCategory"] = errors_gdf["RegionName"]

    # Group by RegionCategory
    for region, group in errors_gdf.groupby("RegionCategory"):
        errors = group["Error_m"]
        match_found = group["MatchFnd"]

        # Calculate statistics for matched points only
        matched_errors = errors[match_found]
        n_matched = len(matched_errors)
        n_unmatched = len(match_found) - n_matched  # Total points minus matched points

        if n_matched > 0:
            mean_error = matched_errors.mean()
            std_dev_error = matched_errors.std()
            median_error = matched_errors.median()
            perc_90 = np.percentile(matched_errors.dropna(), 90)
            perc_95 = np.percentile(matched_errors.dropna(), 95)
            max_error = matched_errors.max()
        else:
            # Handle cases with no matches
            mean_error = std_dev_error = median_error = perc_90 = perc_95 = max_error = None

        print(f"{region} Error Statistics:")
        print(f"  Total Number of Points: {len(match_found)}")
        print(f"  Matched Points (n): {n_matched}")
        print(f"  Unmatched Points (n): {n_unmatched}")
        if n_matched > 0:
            print(f"  Mean Error (m): {mean_error:.2f}")
            print(f"  Std Dev Error (m): {std_dev_error:.2f}")
            print(f"  Median Error (m): {median_error:.2f}")
            print(f"  90th Percentile Error (m): {perc_90:.2f}")
            print(f"  95th Percentile Error (m): {perc_95:.2f}")
            print(f"  Maximum Error (m): {max_error:.2f}")
        else:
            print("  No matches found in this region.")
        print()


def generate_cdf_by_regions(errors_gdf, output_cdf, shapefile_name):
    """
    Generate a cumulative distribution plot for each region category.
    """
    errors_gdf["RegionCategory"] = errors_gdf["RegionName"]

    # Define a list of line styles to cycle through
    line_styles = ['-', '--', (0, (3, 1, 1, 1))]
    # If you have more than 12 regions, the list above will cycle

    plt.figure(figsize=(8, 5), dpi=200)
    for i, (region, group) in enumerate(errors_gdf.groupby("RegionCategory")):
        errors = group["Error_m"].clip(lower=2.5)
        sorted_errors = np.sort(errors.to_numpy())
        cumulative = np.arange(1, len(sorted_errors) + 1) / len(sorted_errors) * 100

        linestyle = line_styles[i % len(line_styles)]
        plt.plot(sorted_errors, cumulative, linewidth=2, label=f"{region} n={len(group)}", linestyle=linestyle)

    plt.xscale("log")
    plt.xlabel("Error Distance (m)", fontsize=LABEL_FONTSIZE)
    plt.ylabel("Cumulative Percentage (%)", fontsize=LABEL_FONTSIZE)
    plt.title(f"Digitisation boundary error by region\n{shapefile_name}", fontsize=TITLE_FONTSIZE)
    plt.yticks(np.arange(0, 101, 10), fontsize=TICK_FONTSIZE)
    plt.gca().yaxis.set_minor_locator(plt.MultipleLocator(5))
    plt.ylim(0, 100)
    plt.xlim(left=3)
    plt.xticks(fontsize=TICK_FONTSIZE)
    plt.yticks(fontsize=TICK_FONTSIZE)
    plt.grid(True, which="both", ls="--", linewidth=0.5)
    plt.legend(
        loc="lower right",
        fontsize=int(LEGEND_FONTSIZE * 0.9),  # 70% of original size
        framealpha=0.9,
        borderaxespad=0.5,
        labelspacing=0.5,
        handlelength=2,
        handletextpad=0.5,
        borderpad=0.5
    )
    plt.tight_layout()

    plt.savefig(output_cdf)
    plt.close()
    print(f"Cumulative distribution plot saved to {output_cdf}")

def generate_cdf_combined_with_regional_background(errors_gdf, output_cdf, shapefile_name):
    """
    Plot all regional CDFs as grey background lines, and the combined CDF as a prominent line.
    """
    errors_gdf["RegionCategory"] = errors_gdf["RegionName"]

    plt.figure(figsize=(8, 5), dpi=200)

    # Plot each region as a thin, semi-transparent grey line
    for region, group in errors_gdf.groupby("RegionCategory"):
        errors = group["Error_m"].clip(lower=2.5)
        sorted_errors = np.sort(errors.to_numpy())
        cumulative = np.arange(1, len(sorted_errors) + 1) / len(sorted_errors) * 100
        plt.plot(
            sorted_errors,
            cumulative,
            color="grey",
            linewidth=1,
            alpha=0.4,
            zorder=1
        )

    # Add a dummy grey line for the legend
    plt.plot([], [], color="grey", linewidth=2, alpha=0.4, label="Individual regions")

    # Plot the combined CDF for all data as a prominent line
    all_errors = errors_gdf["Error_m"].clip(lower=2.5)
    sorted_all_errors = np.sort(all_errors.to_numpy())
    cumulative_all = np.arange(1, len(sorted_all_errors) + 1) / len(sorted_all_errors) * 100
    plt.plot(
        sorted_all_errors,
        cumulative_all,
        color="blue",
        linewidth=2.5,
        label=f"All regions (n={len(all_errors)})",
        zorder=2
    )

    plt.xscale("log")
    plt.xlabel("Error Distance (m)", fontsize=LABEL_FONTSIZE)
    plt.ylabel("Cumulative Percentage (%)", fontsize=LABEL_FONTSIZE)
    plt.title(f"Digitisation boundary error (all regions)\n{shapefile_name}", fontsize=TITLE_FONTSIZE)
    plt.yticks(np.arange(0, 101, 10), fontsize=TICK_FONTSIZE)
    plt.gca().yaxis.set_minor_locator(plt.MultipleLocator(5))
    plt.ylim(0, 100)
    plt.xlim(left=3)  # Start x-axis at 3 m
    plt.xticks(fontsize=TICK_FONTSIZE)
    plt.yticks(fontsize=TICK_FONTSIZE)
    plt.grid(True, which="both", ls="--", linewidth=0.5)
    plt.legend(
        loc="lower right",
        fontsize=int(LEGEND_FONTSIZE * 0.9),
        framealpha=0.9,
        borderaxespad=0.5,
        labelspacing=0.5,
        handlelength=2,
        handletextpad=0.5,
        borderpad=0.5
    )
    plt.tight_layout()
    plt.savefig(output_cdf)
    plt.close()
    print(f"Combined CDF plot saved to {output_cdf}")



def plot_all_assessment_cdfs(assessments, output_path):
    """
    Plot the 'All regions' CDF for each assessment on a single figure.
    """
    plt.figure(figsize=(8, 5), dpi=200)
    colors = plt.cm.viridis(np.linspace(0, 1, len(assessments)))
    for i, assessment in enumerate(assessments):
        base_filename = os.path.splitext(os.path.basename(assessment["input"]))[0]
        csv_path = f"{assessment['output_dir']}/{base_filename}_pos-err.csv"
        if not os.path.exists(csv_path):
            print(f"[WARNING] CSV not found for {assessment['name']}: {csv_path}")
            continue
        df = pd.read_csv(csv_path)
        errors = df["Error_m"].clip(lower=2.5)
        sorted_errors = np.sort(errors.to_numpy())
        cumulative = np.arange(1, len(sorted_errors) + 1) / len(sorted_errors) * 100
        plt.plot(
            sorted_errors,
            cumulative,
            label=f"{assessment['name']} (n={len(errors)})",
            color=colors[i],
            linewidth=2
        )
    plt.xscale("log")
    plt.xlabel("Error Distance (m)", fontsize=LABEL_FONTSIZE)
    plt.ylabel("Cumulative Percentage (%)", fontsize=LABEL_FONTSIZE)
    plt.title("All regions: Cumulative boundary error by assessment", fontsize=TITLE_FONTSIZE)
    plt.yticks(np.arange(0, 101, 10), fontsize=TICK_FONTSIZE)
    plt.gca().yaxis.set_minor_locator(plt.MultipleLocator(5))
    plt.ylim(0, 100)
    plt.xlim(left=3)  # Start x-axis at 3 m
    plt.xticks(fontsize=TICK_FONTSIZE)
    plt.yticks(fontsize=TICK_FONTSIZE)
    plt.grid(True, which="both", ls="--", linewidth=0.5)
    plt.legend(loc="lower right", fontsize=10)
    plt.tight_layout()
    plt.savefig(output_path)
    plt.close()
    print(f"All-assessment CDF plot saved to {output_path}")

def generate_edge_accuracy_scatter(errors_gdf, output_path, shapefile_name):
    """
    Scatter plot: EdgeAcc_m vs Error_m (log-log), coloured by RegionName, with global log-log regression.
    Adds:
      - Diagonal y = x (feature edge accuracy equals boundary error).
      - Percentage of points where Error_m > EdgeAcc_m.
      - Regression power-law equation and R^2.
    """
    if "EdgeAcc_m" not in errors_gdf.columns:
        return
    df = errors_gdf.copy()
    df = df[(df["EdgeAcc_m"].notna()) & (df["Error_m"].notna()) &
            (df["EdgeAcc_m"] > 0) & (df["Error_m"] > 0)]
    if df.empty or df["EdgeAcc_m"].nunique() < 2 or df["Error_m"].nunique() < 2:
        print("Skipping edge accuracy scatter plot (insufficient data).")
        return

    # Compute exceedance percentage
    pct_exceed = 100.0 * (df["Error_m"] > df["EdgeAcc_m"]).mean()
    print(f"Percentage of points where boundary error exceeds edge accuracy: {pct_exceed:.1f}%")

    plt.figure(figsize=(6.5, 5), dpi=200)
    regions = df["RegionName"].fillna("Unknown").unique()
    cmap = plt.cm.get_cmap("tab20", len(regions))
    region_color = {r: cmap(i) for i, r in enumerate(regions)}

    for r, g in df.groupby("RegionName"):
        plt.scatter(g["EdgeAcc_m"], g["Error_m"],
                    s=25, alpha=0.5, color=region_color[r],
                    label=r, edgecolors='none')

    # Log-log regression (power law)
    log_x = np.log10(df["EdgeAcc_m"])
    log_y = np.log10(df["Error_m"])
    a, b = np.polyfit(log_x, log_y, 1)          # log10(y) = a*log10(x) + b
    c = 10 ** b                                  # y = c * x^a
    x_line = np.linspace(df["EdgeAcc_m"].min(), df["EdgeAcc_m"].max(), 200)
    y_line = c * (x_line ** a)
    plt.plot(x_line, y_line, color="red", linewidth=2, label="Log-log regression")

    # R^2 in log space
    log_y_pred = a * log_x + b
    ss_res = np.sum((log_y - log_y_pred) ** 2)
    ss_tot = np.sum((log_y - log_y.mean()) ** 2)
    r2 = 1 - ss_res / ss_tot if ss_tot != 0 else np.nan

    # Diagonal y = x (reference)
    diag_min = min(df["EdgeAcc_m"].min(), df["Error_m"].min())
    diag_max = max(df["EdgeAcc_m"].max(), df["Error_m"].max())
    diag_x = np.array([diag_min, diag_max])
    plt.plot(diag_x, diag_x, linestyle=":", color="black", linewidth=1.2, label="y = x")

    plt.xscale("log")
    plt.yscale("log")
    plt.xlabel("Feature edge accuracy (m)", fontsize=LABEL_FONTSIZE)
    plt.ylabel("Boundary error (m)", fontsize=LABEL_FONTSIZE)
    plt.title(f"Edge accuracy vs boundary error\n{shapefile_name}", fontsize=TITLE_FONTSIZE)

    # Annotation (axes coordinates)
    annotation = (f"y = {c:.2f} * x^{a:.2f}\n"
                  f"R² = {r2:.2f}\n"
                  f"Pct(Error > EdgeAcc) = {pct_exceed:.1f}%")
    plt.text(0.03, 0.97, annotation, ha="left", va="top",
             transform=plt.gca().transAxes, fontsize=10,
             bbox=dict(facecolor='white', alpha=0.7, edgecolor='none', pad=4))

    plt.legend(fontsize=LEGEND_FONTSIZE * 0.6, framealpha=0.9, ncol=2)
    plt.grid(True, which="both", ls="--", linewidth=0.5)
    plt.tight_layout()
    plt.savefig(output_path)
    plt.close()
    print(f"Edge accuracy scatter plot saved to {output_path}")


if __name__ == "__main__":
    for assessment in ASSESSMENTS:
        print(f"Running assessment: {assessment['name']}")
        os.makedirs(assessment["output_dir"], exist_ok=True)
        base_filename = os.path.splitext(os.path.basename(assessment["input"]))[0]
        output_csv = f"{assessment['output_dir']}/{base_filename}_pos-err.csv"
        output_cdf = f"{assessment['output_dir']}/{base_filename}_error_cdf.png"
        match_points_shp = f"{assessment['output_dir']}/{base_filename}_match_pnts.shp"
        output_cdf_combined = f"{assessment['output_dir']}/{base_filename}_error_cdf_combined.png"
        output_edge_acc_scatter = f"{assessment['output_dir']}/{base_filename}_edge-acc_vs_error.png"
        output_edge_acc_scatter_linear = f"{assessment['output_dir']}/{base_filename}_edge-acc_vs_error_linear.png"

        distances_with_regions = calculate_distances_with_regions(
            assessment["input"], assessment["gtp"], assessment["regions"],
            output_csv, match_points_shp, edge_acc_var=assessment.get("edge_acc_var")
        )
        if distances_with_regions is not None:
            output_error_statistics_by_region(distances_with_regions)
            generate_cdf_by_regions(distances_with_regions, output_cdf, base_filename)
            generate_cdf_combined_with_regional_background(distances_with_regions, output_cdf_combined, base_filename)

            # New scatter plot (only if edge accuracy attribute configured)
            if assessment.get("edge_acc_var"):
                generate_edge_accuracy_scatter(distances_with_regions, output_edge_acc_scatter, base_filename)
                
    output_all_assessments_cdf = "working/22/all_assessments_error_cdf.png"
    plot_all_assessment_cdfs(ASSESSMENTS, output_all_assessments_cdf)
